version: '3.8'
services:
  nginx-rtmp:
    container_name: nginx_rtmp_server
    build: ./nginx-rtmp
    ports:
      - '1935:1935' # RTMP 포트
      - '8080:8080' # HLS 포트
    volumes:
      - ./nginx-rtmp/hls:/tmp/hls

  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    command: npm run dev

  mysql:
  image: mysql:latest
  container_name: mysql-prod
  environment:
    MYSQL_ROOT_PASSWORD: yourpassword
    MYSQL_DATABASE: overhangstream
  ports:
    - '3306:3306'
  volumes:
    - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
